---

AWSTemplateFormatVersion: '2010-09-09'


Description: Pipeline for IAM user stacks


Parameters:
  GithubOauthToken:
    Description: The personal access token of the GitHub source repo
    NoEcho: true
    Type: String


Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration:
        Status: Enabled

  FullAccessCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Ref: ArtifactStoreBucket
        Type: S3
      Name: iam-pipeline
      RoleArn:
        Fn::GetAtt:
        - PipelineRole
        - Arn
      Stages:
      - Name: Source-Stage
        Actions:
        - Name: Source-Action
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          Configuration:
            Branch: master
            OAuthToken:
              Ref: GithubOauthToken
            Owner: BhargavAmin
            Repo: iam-access-multi-account-architecture
          InputArtifacts: []
          OutputArtifacts:
          - Name: SourceOutput

      - Name: Pipeline-Stage
        Actions:
        - Name: Pipeline-Action
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
            ParameterOverrides:
              Fn::Sub: |
                {
                  "GithubOauthToken": "${GithubOauthToken}"
                }
            RoleArn:
              Fn::GetAtt:
              - FullAccessCloudFormationRole
              - Arn
            StackName:
              Ref: AWS::StackName
            TemplatePath: SourceOutput::jump-account/pipeline.yaml
          InputArtifacts:
          - Name: SourceOutput
          RunOrder: 1

      - Name: IAM-Group-Stage
        Actions:
        - Name: iam-group
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn:
              Fn::GetAtt:
              - FullAccessCloudFormationRole
              - Arn
            StackName: iam-group
            TemplatePath: SourceOutput::jump-account/iam-groups.yaml
          InputArtifacts:
          - Name: SourceOutput
          RunOrder: 1

      - Name: IAM-User-Stage
        Actions:
        - Name: iam-users
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn:
              Fn::GetAtt:
              - FullAccessCloudFormationRole
              - Arn
            StackName: iam-users
            TemplatePath: SourceOutput::jump-account/iam-users.yaml
          InputArtifacts:
          - Name: SourceOutput
          RunOrder: 1

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /

...
